 /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Color } from 'three'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Back_Down.geometry} material={materials.Main_} position={[0.35, -0.46, 1.02]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Back_Little_Part.geometry} material={materials.Main_} position={[0.68, 0.2, 0.98]} rotation={[1.56, 0.07, Math.PI / 2]} />
      <mesh geometry={nodes.Back_Mid.geometry} material={materials.Main_} position={[-0.08, 0.53, 1.1]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Back_Top_.geometry} material={materials.Main_} position={[0.09, 0.86, 1.07]} rotation={[Math.PI, -0.26, Math.PI]} />
      <mesh geometry={nodes.Central_.geometry} material={materials.Main_} position={[-0.51, -0.23, 1.18]} rotation={[Math.PI, -0.34, Math.PI]} />
      <mesh geometry={nodes.Circle.geometry} material={materials.Main_} position={[-2.29, -1.26, 0.92]} rotation={[Math.PI / 2, 0, -2.05]} />
      <mesh geometry={nodes.Down_With_Holes.geometry} material={materials.Main_} position={[-1.83, -0.39, 1.3]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Front_part_.geometry} material={materials.Main_} position={[-2.59, -0.7, 1.2]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Front_With_Holes.geometry} material={materials.Main_} position={[-2.61, -0.47, 1.21]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Inserts.geometry} material={materials.Main_} position={[-0.36, 0.24, 1.11]} rotation={[Math.PI, -0.34, Math.PI]} />
      <mesh geometry={nodes.Label_Back.geometry} material={materials.Main_} position={[-0.65, 1.03, 1.16]} rotation={[Math.PI / 2, -1.02, Math.PI / 2]} />
      <mesh geometry={nodes.Label_Front.geometry} material={materials.Main_} position={[-0.71, 1.26, 1.21]} rotation={[1.6, -0.91, 1.6]} />
      <mesh geometry={nodes.Logo.geometry} material={materials.Main_} position={[-0.1, 0.51, 1.74]} rotation={[0.11, 0.21, -0.36]} />
      <mesh geometry={nodes.Main_sole.geometry} material={materials.Main_} position={[-1.36, -1.23, 1.14]} rotation={[Math.PI / 2, 0, -2.05]} />
      <mesh geometry={nodes.Middle_With_Holes.geometry} material={materials.Main_} position={[-0.98, 0.38, 1.19]} rotation={[Math.PI / 2, 0.6, -Math.PI]} />
      <mesh geometry={nodes.Nike_.geometry} material={materials.Main_} position={[-0.19, -0.15, 1.08]} rotation={[Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes.Nike_Logo.geometry} material={materials.Main_} position={[-1.13, -1.25, 1.28]} rotation={[Math.PI / 2, 0, -2.05]} />
      <mesh geometry={nodes.Seams.geometry} material={materials.Main_} position={[-1.34, -0.91, 1.16]} rotation={[-1.57, -0.02, -1.57]} scale={0.04} />
      <mesh geometry={nodes.Shoelace.geometry} material={materials.Main_} position={[-1.37, 0.2, 1.21]} rotation={[-Math.PI, 1.56, -Math.PI]} />
      <mesh geometry={nodes.Tongue.geometry} material={materials.Main_} position={[-0.95, 0.44, 1.23]} rotation={[Math.PI / 2, -1.02, Math.PI / 2]} /> 
      <mesh geometry={nodes.Top_Round_.geometry} material={materials.Main_} position={[-0.03, 1.03, 1.09]} rotation={[Math.PI, -0.26, Math.PI]} />
      <mesh geometry={nodes.Tubes.geometry} material={materials.Main_} position={[-2.32, -1.23, 1.16]} rotation={[Math.PI / 2, 0, -2.05]} />
      <mesh geometry={nodes.Under_feet.geometry} material={materials.Main_} position={[-1.2, -0.93, 1.13]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Under_Sole_Plate.geometry} material={materials.Main_} position={[-1.28, -1.19, 1.18]} rotation={[Math.PI / 2, 0, -2.05]} />
      <mesh geometry={nodes.Back_Down001.geometry} material={materials.Main_} position={[0.38, -0.46, -1.02]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Back_Little_Part001.geometry} material={materials.Main_} position={[0.71, 0.2, -0.98]} rotation={[-1.56, -0.07, -Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Back_Mid001.geometry} material={materials.Main_} position={[-0.04, 0.53, -1.1]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.Back_Top_001.geometry} material={materials.Main_} position={[0.12, 0.86, -1.07]} rotation={[-Math.PI, 0.26, 0]} scale={-1} />
      <mesh geometry={nodes.Central_001.geometry} material={materials.Main_} position={[-0.48, -0.23, -1.18]} rotation={[-Math.PI, 0.34, 0]} scale={-1} />
      <mesh geometry={nodes.Circle001.geometry} material={materials.Main_} position={[-2.26, -1.26, -0.92]} rotation={[-Math.PI / 2, 0, 1.09]} scale={-1} />
      <mesh geometry={nodes.Down_With_Holes001.geometry} material={materials.Main_} position={[-1.8, -0.39, -1.3]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Front_part_001.geometry} material={materials.Main_} position={[-2.56, -0.7, -1.2]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Front_With_Holes001.geometry} material={materials.Main_} position={[-2.57, -0.47, -1.21]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.Inserts001.geometry} material={materials.Main_} position={[-0.33, 0.24, -1.11]} rotation={[-Math.PI, 0.34, 0]} scale={-1} />
      <mesh geometry={nodes.Label_Back001.geometry} material={materials['Material.001']} position={[-0.62, 1.03, -1.16]} rotation={[-Math.PI / 2, 1.02, -Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Label_Front001.geometry} material={materials['Material.001']} position={[-0.68, 1.26, -1.21]} rotation={[-1.6, 0.91, -1.54]} scale={-1} />
      <mesh geometry={nodes.Logo001.geometry} material={materials.Main_} position={[-0.07, 0.51, -1.74]} rotation={[-0.11, -0.21, 2.78]} scale={-1} />
      <mesh geometry={nodes.Main_sole001.geometry} material={materials.Main_} position={[-1.32, -1.23, -1.14]} rotation={[-Math.PI / 2, 0, 1.09]} scale={-1} />
      <mesh geometry={nodes.Middle_With_Holes001.geometry} material={materials.Main_} position={[-0.95, 0.38, -1.19]} rotation={[-Math.PI / 2, -0.6, 0]} scale={-1} />
      <mesh geometry={nodes.Nike_001.geometry} material={materials.Main_} position={[-0.16, -0.15, -1.08]} rotation={[-Math.PI / 2, 0, 0]} scale={-1} />
      <mesh geometry={nodes.Nike_Logo001.geometry} material={materials.Main_} position={[-1.1, -1.25, -1.28]} rotation={[-Math.PI / 2, 0, 1.09]} scale={-1} />
      <mesh geometry={nodes.Seams001.geometry} material={materials.Main_} position={[-1.31, -0.91, -1.16]} rotation={[1.57, 0.02, 1.57]} scale={-0.04} />
      <mesh geometry={nodes.Shoelace001.geometry} material={materials.Main_} position={[-1.34, 0.2, -1.21]} rotation={[Math.PI, -1.56, 0]} scale={-1}/>
      <mesh geometry={nodes.Tongue001.geometry} material={materials.Main_} position={[-0.92, 0.44, -1.23]} rotation={[-Math.PI / 2, 1.02, -Math.PI / 2]} scale={-1} />
      <mesh geometry={nodes.Top_Round_001.geometry} material={materials.Main_} position={[0.01, 1.03, -1.09]} rotation={[-Math.PI, 0.26, 0]} scale={-1} />
      <mesh geometry={nodes.Tubes001.geometry} material={materials.Main_} position={[-2.29, -1.23, -1.16]} rotation={[-Math.PI / 2, 0, 1.09]} scale={-1} />
      <mesh geometry={nodes.Under_feet001.geometry} material={materials.Main_} position={[-1.17, -0.93, -1.13]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.Under_Sole_Plate001.geometry} material={materials.Main_} position={[-1.25, -1.19, -1.18]} rotation={[-Math.PI / 2, 0, 1.09]} scale={-1} />
    </group>
  )
}

useGLTF.preload('/model.glb')
